src/genius/urls.py
from django import urls
from django.urls import path
from genius.views import (home, Class_create, Class_Update, Class_Delete, Class_Detail, Classes, Add_name,
                          Student_Main, Student_Create, Student_Update, Student_Delete, Student_Detail, Search)

app_name = 'genius'

urlpatterns = [
    path('', home, name='home'),
    path('class/', Classes, name='class'),
    path('class/add-name', Add_name, name='add-name'),
    path('class/create', Class_create, name='create-class'),
    path('class/<int:id>', Class_Detail, name='detail'),
    path('class/<int:id>/edit/', Class_Update, name='update'),
    path('class/<int:id>/delete/', Class_Delete, name='delete'),
    path('stds/', Student_Main, name='stds'),
    path('stds/create', Student_Create, name='stds-new'),
    path('stds/<int:id>',Student_Detail , name='std-detail'),
    path('stds/search/',Search , name='std-search'),
    path('stds/<int:id>/edit/', Student_Update, name='std-update'),
    path('stds/<int:id>/delete/', Student_Delete, name='std-delete'),
]

src/littleHead/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('genius.urls')),
]

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

    <title>{% block head_title %}
    {% endblock head_title %}</title>
    
  </head>
  <body class="bg-dark text-light">

    {% include 'navbar.html' %}
    
    <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible" role="alert" id="alert">
                    <button class="close" data-dismiss="alert">
                        <small><sup>x</sup></small>
                    </button>
                {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock content %}
    </div>

    
    {% include 'js.html' %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
    <script>
      function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>
    {% block javascript %}
    {% endblock javascript %}
    
  </body>
</html>

src/templates/js.html
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning mb-4">
  <a class="navbar-brand head font-weight-bold" href="/">Little Genius</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'genius:class'%}">Classes</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'genius:stds'%}">Students</a>
      </li>
      
      
  </div>
  
</nav>

{% comment %} <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> {% endcomment %}