src/genius/urls.py
from django import urls
from django.urls import path
from genius.views import (home, Class_create, Class_Update, Class_Delete, Class_Detail, Classes, Add_name,
                          Student_Main, Student_Create, Student_Update, Student_Delete, Student_Detail, Search)

app_name = 'genius'

urlpatterns = [
    path('', home, name='home'),
    path('class/', Classes, name='class'),
    path('class/add-name', Add_name, name='add-name'),
    path('class/create', Class_create, name='create-class'),
    path('class/<int:id>', Class_Detail, name='detail'),
    path('class/<int:id>/edit/', Class_Update, name='update'),
    path('class/<int:id>/delete/', Class_Delete, name='delete'),
    path('stds/', Student_Main, name='stds'),
    path('stds/create', Student_Create, name='stds-new'),
    path('stds/<int:id>',Student_Detail , name='std-detail'),
    path('stds/search/',Search , name='std-search'),
    path('stds/<int:id>/edit/', Student_Update, name='std-update'),
    path('stds/<int:id>/delete/', Student_Delete, name='std-delete'),
]

src/littleHead/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('genius.urls')),
]

src/genius/forms.py
from django import forms
from .models import Create_Class, Name_of_classes, Students


class Creat_Class_Form(forms.Form):
    class_name = forms.CharField()
    from_days = forms.DateField()
    to_days = forms.DateField()
    from_time = forms.TimeField()
    to_time = forms.TimeField()


class Create_Class_Model_Form(forms.ModelForm):
    class Meta:
        model = Create_Class
        exclude = ['created_by', 'created_on','class_name']
        fields = ['class_name', 'from_days', 'to_days', 'from_time', 'to_time']
        # names = Name_of_classes.objects.values_list('name').distinct()
        #classname = list(names)
        from_choice = [
            ('Mon', 'Monday'),
            ('Tue', 'Tuesday'),
            ('Wed', 'Wednesday'),
            ('Thu', 'Thursday'),
            ('Fri', 'Friday'),
            ('Sat', 'Saturday'),
            ('Sun', 'Sunday'),
        ]
        # print('\nType is :')
        # print(type(from_choice))
        # print(classname)
        widgets = {
            #'class_name': forms.TextInput(attrs={'class': 'form-control'}),
            'from_days': forms.DateTimeInput(attrs={'class': 'from-date form-control'}),
            'to_days': forms.DateTimeInput(attrs={'class': 'from-date form-control'}),
            'from_time': forms.DateTimeInput(attrs={'class': 'from-time form-control'}),
            'to_time': forms.DateTimeInput(attrs={'class': 'from-time form-control'}),
        }


class Student_Model_Form(forms.ModelForm):
    class Meta:
        model = Students
        fields = ('__all__')
        exclude = ('created_by', 'age')
        grade_choice = (
            ('G1', 'Grade-1'),
            ('G2', 'Grade-2'),
            ('G3', 'Grade-3'),
            ('G4', 'Grade-4'),
            ('G5', 'Grade-5'),
            ('G6', 'Grade-6'),
            ('G7', 'Grade-7'),
            ('G8', 'Grade-8'),
            ('G9', 'Grade-9'),
            ('G10', 'Grade-10'),
            ('G11', 'Grade-11'),
            ('G12', 'Grade-12'),
        )
        gender_choice=(
        ('M', 'Male'),
        ('F', 'Female'),
        ('N', 'None'),
    )
        relation_choice=(
        ('Uncle', 'Uncle'),
        ('Aunty', 'Aunty'),
        ('Father', 'Father'),
        ('Mother', 'Mother'),
        ('Grandpa', 'Grandpa'),
        ('Grandma', 'Grandma'),
        ('Sister', 'Sister'),
        ('Brother', 'Brother'),
    )
        blood_choice=(
        ('O', 'O'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('A+', 'A+'),
        ('AB', 'AB'),
    )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'dob': forms.DateTimeInput(attrs={'class': 'datetime-input form-control'}),
            'grade': forms.Select(choices=grade_choice, attrs={'class': 'form-control'}),
            'attending_school': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'gender': forms.Select(choices=gender_choice, attrs={'class': 'form-control'}),
            'parent_name':forms.TextInput(attrs={'class': 'form-control'}),
            'parent_contact': forms.TextInput(attrs={'class': 'form-control'}),
            'parent_address': forms.Textarea(attrs={'class': 'form-control', 'rows':3}),
            'emerg_name': forms.TextInput(attrs={'class': 'form-control'}),
            'emerg_contact':forms.TextInput(attrs={'class': 'form-control'}),
            'emerg_relation': forms.Select(choices=relation_choice,attrs={'class': 'form-control'}),
            'doc_name': forms.TextInput(attrs={'class': 'form-control'}),
            'doc_contact': forms.TextInput(attrs={'class': 'form-control'}),
            'blood_type':forms.Select(choices=blood_choice,attrs={'class': 'form-control'}),
            'allergic': forms.Textarea(attrs={'class': 'form-control', 'rows':3}),
        }
    def __init__(self, *args, **kwargs):
        super(Student_Model_Form, self).__init__(*args, **kwargs)
        self.fields['course']=forms.ModelChoiceField(queryset=Create_Class.objects.all(), label='Select Class', widget=forms.Select(attrs={'class':'form-control'}),help_text='If you are facing in choosing Class, detail is avaiable below.')

src/genius/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Create_Class, Name_of_classes, Students
from .forms import (Creat_Class_Form, Create_Class_Model_Form,
                    Student_Model_Form)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count
from django.http import JsonResponse, HttpResponse
from datetime import datetime, date
import datetime as dt

from datetime import timedelta
from django.utils import timezone
# Create your views here.


def home(request):
    fieldname = 'class_name'
    to_bday, tmr_bday = Birthday_alert()
    #tmr_bday, to_bday = Birthday_alert()
    objs = Create_Class.objects.values(fieldname).order_by(
        fieldname).annotate(the_count=Count(fieldname))
    # print(objs)
    template_name = 'genius/home.html'
    context = {'head_title': "Little Genius",
               'data': 'Little Genius-School of Science & Technology',
               'count': objs,
               'tmr':tmr_bday,
               'to':to_bday,
               }
    return render(request, template_name, context)


def Add_name(request):
    if request.method == 'POST':
        print('JS got here')
        class_name = request.POST['class-name']
        print(class_name)
        data = None
        if len(class_name) > 0:
            is_there = Name_of_classes.objects.filter(name__iexact=class_name)
            if not is_there:
                inst = Name_of_classes.objects.create(name=class_name)
                data = {
                    'bool': True,
                    'msg': 'Created Successfully'
                }
            else:
                data = {
                    'bool': False,
                    'msg': 'Name already exists!'
                }
        else:
            data = {
                'bool': False,
                'msg': 'Name should not be empty!'
            }
        return JsonResponse(data)
    else:
        print('JS has not arrived')
        return redirect('/')


def Classes(request):
    objs = Create_Class.objects.all()
    names = Name_of_classes.objects.all()
    templatename = 'genius/classes.html'
    context = {'classes': objs, 'class': names}
    return render(request, templatename, context)

# @login_required(login_url='/login/')


def Class_create(request):
    form = Create_Class_Model_Form(request.POST or None)
    name = request.POST.get('select')
    fromday = request.POST.get('from_days')
    today = request.POST.get('to_days')
    fromtime = request.POST.get('from_time')
    to_time = request.POST.get('to_time')
    # get class_names from classname table
    fieldname = 'class_name'
    objs = Create_Class.objects.values(fieldname).order_by(
        fieldname).annotate(the_count=Count(fieldname))
    # Check whether data already exists in database
    already = Create_Class.objects.filter(
        class_name__iexact=name).filter(from_days__iexact=fromday).filter(to_days__iexact=today).filter(from_time__iexact=fromtime).filter(to_time__iexact=to_time)
    if not already:
        if name != "Click to select Class Name":
            if form.is_valid():
                obj = form.save(commit=False)
                obj.class_name = name
                #obj.created_by = request.user.username
                obj.save()
                print('successful')
                messages.success(request, 'Saved Successfully')
                form = Create_Class_Model_Form()
            else:
                #messages.error(request, 'Something wrong with data')
                form = Create_Class_Model_Form()

        else:
            messages.error(request, 'Please select the class name')
    else:
        messages.error(request, 'This class already exists')
    c_names = Name_of_classes.objects.values('name')
    templatename = 'genius/class_create.html'
    context = {'form': form, 'c_names': c_names, 'count': objs}
    return render(request, templatename, context)


def Class_Detail(request, id):
    objs = get_object_or_404(Create_Class, id=id)
    templatename = 'genius/class_detail.html'
    context = {'obj': objs, 'form': None}
    return render(request, templatename, context)


def Class_Update(request, id):
    obj = get_object_or_404(Create_Class, id=id)
    form = Create_Class_Model_Form(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        messages.success(request, 'Class Updated Successfully.')
    templatename = 'genius/class_update.html'
    context = {'form': form,
               'head_title': f"Update {obj.class_name}",
               'title': f"Update : {obj.class_name}"}
    return render(request, templatename, context)


def Class_Delete(request, id):
    objs = get_object_or_404(Create_Class, id=id)
    templatename = 'genius/class_delete.html'
    if request.method == "POST":
        objs.delete()
        return redirect("/class")
    context = {'obj': objs, 'form': None}
    return render(request, templatename, context)


def Student_Main(request):
    objs= Students.objects.values().all()
    std_count=Students.objects.all().count()
    template_name = 'genius/students.html'
    context = {'head_title': 'Little Genius Students', 'students':objs,'count':std_count}
    return render(request, template_name, context)


def Student_Create(request):
    form = Student_Model_Form(request.POST or None)
    print('Student view came')
    cls=get_class_parent_detail()
    if request.method =='POST':
        # get class names and days
        for_age= form.data['dob']
        to_date=datetime.strptime(for_age, '%Y-%m-%d').date()
        get_age=Calculate_Age(to_date)
        print('MEthod is post')
        #now start storing the Student information
        print(form.data)
        if form.is_valid():
            print('form is valid')
            obj = form.save(commit=False)
            obj.age = get_age
            obj.save()
            messages.success(request, 'Student is registered successfully')
            form=Student_Model_Form()   
        else:
            messages.error(request,form.errors)
            print(form.errors)  
    template_name = 'genius/students_create.html'
    context = {'form': form,'classes':cls}
    return render(request, template_name, context)

def Student_Detail(request, id):
    objs = get_object_or_404(Students, id=id)
    templatename = 'genius/students_detail.html'
    context = {'obj': objs, 'form': None}
    return render(request, templatename, context)

def Student_Update(request, id):
    obj = get_object_or_404(Students, id=id)
    form = Student_Model_Form(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        messages.success(request, 'Student Updated Successfully.')
        return redirect('/stds')
    templatename = 'genius/student_update.html'
    context = {'form': form,
               'head_title': f"Update {obj.name}",
               'title': f"Update : {obj.name}"}
    return render(request, templatename, context)

def Student_Delete(request, id):
    objs = get_object_or_404(Students, id=id)
    templatename = 'genius/students_delete.html'
    if request.method == "POST":
        objs.delete()
        messages.success(request,'Deleted Successfully.')
        return redirect("/stds")
    context = {'obj': objs, 'form': None}
    return render(request, templatename, context)


def get_class_parent_detail():
    classes= Create_Class.objects.values('pk','class_name','from_days','to_days','from_time','to_time').all()
    return classes

def Calculate_Age(bday):
    today = date.today() 
    age = today.year - bday.year - ((today.month, today.day) < (bday.month, bday.day)) 
    return age

def Birthday_alert():
    #students= Students.objects.all()
    datetime_now = timezone.now()
    now_day, now_month = datetime_now.day, datetime_now.month
    datetime_tomorrow = datetime_now + timedelta(days=1)
    tomorrow_day, tomorrow_month = datetime_tomorrow.day, datetime_tomorrow.month

    std_today = Students.objects.filter(dob__day=now_day, dob__month=now_month)
    std_tmr = Students.objects.filter(dob__day=tomorrow_day, dob__month=tomorrow_month)
    tday=[]
    tmr=[]

    for l in std_today:
        tday.append({
            'name':l.name,
            'course':l.course.class_name,
            'contact':l.parent_contact,
            'dob':l.dob
        })
    

    for l in std_tmr:
        tmr.append({
            'name':l.name,
            'course':l.course.class_name,
            'contact':l.parent_contact,
            'dob':l.dob
        })
   
    # putting into dictionary
    # for s in students:
    #     if s.dob == dt.date.today():
    #         to_bays.append({
    #             'name': 's.name',
    #             'course': 's.course.class_name',
    #             'dob' : 's.dob',
    #             'contact': 's.parent_contact',
    #         })
    #     elif s.dob + dt.timedelta(days=1) == tmr:
    #         tmr_bdays.append({
    #             'name': 's.name',
    #             'course': 's.course.class_name',
    #             'dob' : 's.dob',
    #             'contact': 's.parent_contact',
    #         })
    #     else:
    #         for m in students:
    #             print("else:",m.name)
    return (tday,tmr)
    

def Search(request):
    q= request.GET.get('q',None)
    print(q)
    results = Students.objects.search(query=q).values()
    std_count=Students.objects.all().count()
    template_name = 'genius/students.html'
    context = {'head_title': 'Little Genius Students', 'students':results,'count':std_count}
    return render(request, template_name, context)

src/genius/templates/genius/class_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}

 <style>
        .scroll {
    max-height: 300px;
    overflow-y: auto;
    }
    </style>
    
    <div class="row justify-content-center">
        
        <h1 class="text-center">Create New Class of <br>Little Genius</h1>
    </div>
    <div class="row justify-content-center">
        <div class="col">
            
            <div class="card text-dark">
                    <label class="lead mb-4">Create Little Genius Class</label>
                    <div class="form-group col-12 center">
                        <form method='POST' action='{% url 'genius:create-class' %}'>
                            {% csrf_token %}
                             <select class="custom-select mb-3" name="select">
                                <option selected>Click to select Class Name</option>
                               {% for i in c_names  %}
                               <option value="{{i.name}}">{{i.name}}</option>
                               {% endfor %}
                            </select>
                            {{form.as_p}}
                            <br>
                            <button class="btn btn-warning" type="submit">Create</button>
                            
                        </form>
                    </div>
                
            </div>
        </div>
        <div class="col">
            <div class="card-dark scroll">
                <div class="lead card-header">Classes so far...
                </div>
                <div class= "card-body scrollspy">
                    {% for x in count %}
                    <button type="button" class="btn btn-primary mb-4">
                     {{x.class_name}} <span class="badge badge-light">{{x.the_count}}</span>
                    </button>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>


    
{% endblock content %}

{% block javascript %}
    <script>
        $(function () {
            $('.from-date').datetimepicker({
                format:'YYYY-MM-DD'
            });
        });

        $(function () {
            $('.from-time').datetimepicker({
                format:'LT'
            });
        });
    </script>
{% endblock javascript %}

src/genius/templates/genius/class_delete.html
{% extends 'base.html' %}

{% block content %}
<h1> Are you sure you want to delete the following class?</h1>
<p class="lead">Class Name : {{obj.class_name}}<br>Days : {{obj.from_days}} to {{obj.to_days}}<br>Time : {{obj.from_time}} to {{obj.to_time}}</p>
<form method="POST" action=".">
{% csrf_token %}
<button class="btn btn-danger">Yes, Delete</button>
</form>
{% endblock content %}

src/genius/templates/genius/class_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row ">
    <div class="col">
        <h1 class="ml-4">Delete Class Room</h1>
    </div>
    <div class="col-9 text-center">
        <div class="">
            <div class="card-dark text-light ">
                    <div class="card-body">
                            
                        <p class="lead font-weight-bold">Class Name : {{obj.class_name}}</p>
                        <p class="lead">Class Days : {{obj.from_days}} to {{obj.to_days}}</p>
                        <p class="lead">Class Timing : {{obj.from_time}} to {{obj.to_time}}</p>
                    </div>
                    <div class="card-foot mb-3">
                        <a class="btn btn-primary" href="{{ obj.get_edit_url }}">Edit</a>
                        <a class="btn btn-danger ml-2" href="{{ obj.get_delete_url }}">Delete</a>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

src/genius/templates/genius/class_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <h1>{{title}}</h1>
        </div>
        <div class="col-9">
            <div class="form-group">
                <div class="card text-dark ">
                    <div class="card-body">
                    <form method='POST' class="form-group" action='.'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <br>
                        <button class="btn btn-warning" type="submit">Update</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

{% block javascript %}
    <script>
        $(function () {
            $('.from-date').datetimepicker({
                format:'YYYY-MM-DD'
            });
        });

        $(function () {
            $('.from-time').datetimepicker({
                format:'LT'
            });
        });
    </script>
{% endblock javascript %}

src/genius/templates/genius/classes.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .scroll {
    max-height: 120px;
    overflow-y: auto;
    }
    </style>
    
    <div class="row ml-4">
        <p>
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            View classes
            </button>
            <a class="btn btn-success ml-2" type="button" href="{%url 'genius:create-class'%}">
            Create class
            </a>
            <div class="col-md-3 mb-4">
                <div class="card text-dark">       
                    <div class="form-group col-12 center">
                    <form method="POST" data-url="{%url 'genius:add-name'%}" id="post-form" class="ajax-form">

                        <label class="lead mb-4">Create Class Name</label>
                        <input type="text" name="class-name" class="form-control mb-3 save-data" placeholder="Name" aria-describedby="helpId">
                        <div class="row">
                        <button class="btn btn-success ml-3" id="save-name">Save</button>
                        <p class="badge badge-warning text-wrap ml-2" id="ret_val" ></p>
                        </div>
                    </form>
                    </div>         
                </div>
            </div>

            <div class="col-md-3 mb-4">
                <div class="card text-dark">
                    <div class="card-header">Names of the Classes</div>
                        <div class= "card-body scroll">
                            {% for x in class %}
                            
                            <span class="badge badge-pill badge-primary">{{x.name}}</span>
                            
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </p>
    </div>
    <div class="collapse mb-4" id="collapseExample">
        <div class="card card-body">
            {% if classes %}
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Class Name</th>
                    <th scope="col">Days</th>
                    <th scope="col">Time</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Created On</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in classes %}
                    <tr>
                    <th scope="row">{{i.id}}</th>
                    <td><a href='{{i.get_absolute_url}}'>{{i.class_name}}</a></td>
                    <td>{{i.from_days}} - {{i.to_days}}</td>
                    <td>{{i.from_time}} - {{i.to_time}}</td>
                    <td>{{i.created_by}}</td>
                    <td>{{i.created_on}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class="lead justify">There are no class created so far...</p>
            {% endif %}
        </div>
    </div>
    
        
    
{% endblock content %}

{% block javascript%}
<script>
    $(document).ready(function(){
    var $myform = $(".ajax-form")
    $myform.submit(function(event){
        event.preventDefault();
        var $formData= $(this).serialize();
        console.log($formData);
        var $endpoint= $myform.attr("data-url");
        console.log($endpoint);
      
        $.ajax({
            method:"POST",
            url: $endpoint,
            data: $formData,
            success: handleFormSuccess,
            error :  handleFormError,
        });
        function handleFormSuccess(data, textStatus, jqXHR){
            console.log(data['msg']);
            console.log(textStatus);
            console.log(jqXHR);
            document.getElementById("ret_val").innerHTML = data['msg'];
            setTimeout(function() { $("#ret_val").hide(); }, 3000);
            //$("#ret_val").show();
            
            $myform[0].reset();
        };

        function handleFormError(jqXHR, textStatus, errorThrown){
            console.log(jqXHR);
            console.log(textStatus);
            console.log(errorThrown);
        };
    });
});  
</script>
{% endblock javascript %}

src/genius/templates/genius/home.html
{% extends 'base.html' %}

{% block content %}
    <h1 class='head font-weight-light'>{{data}}</h1>
    <h2 class='head font-weight-light'>Dashboard</h2>
    <div class="row">
        <div class="col">
            <div class="card-dark">
                    <div class="card-header">Birthday Reminder
                    </div>
                    <div class= "card-body scrollspy">
                        {% if to %}
                            <span class="badge badge-danger">Name:{{to.name}}<br>Course:{{to.course}}
                            <br>DOB:{{to.dob}}<br>Contact:{{to.contact}}
                            </span>
                        {% else %}
                            <span class="badge badge-danger">No Birthdays Today.</span>
                        {% endif %}
                        <hr>
                        {% if tmr %}
                            <span class="badge badge-warning">Name:{{tmr.name}}<br>Course:{{tmr.course}}
                            <br>DOB:{{tmr.dob}}<br>Contact:{{tmr.contact}}
                            </span>
                        {% else %}
                            <span class="badge badge-warning">No Birthdays Tomorrow.</span>
                        {% endif %}
                    </div>
                
            </div>
        </div>
        <div class="col">
            <div class="card-dark">
                <div class="card-header">Classes Dashboard
                </div>
                <div class= "card-body scrollspy">
                    {% for x in count %}
                    <button type="button disbaled" class="btn btn-primary mb-4">
                     {{x.class_name}} <span class="badge badge-light">{{x.the_count}}</span>
                    </button>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card-dark">
                <div class="card-header">Fees Reminder
                </div>
                <div class= "card-body">

                </div>
            </div>
        </div>
    </div>
    
    {% comment %} <form action="{% url "genius:home" %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form1.as_p }}
    {{ form2.as_p }}
    <button type="submit" value="Upload">Submit</button>
</form> {% endcomment %}
    
{% endblock content %}

src/genius/templates/genius/student_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <h1>{{title}}</h1>
        </div>
        <div class="col-9">
            <div class="form-group">
                <div class="card text-dark ">
                    <div class="card-body">
                    <form method='POST' class="form-group" action='.'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <br>
                        <button class="btn btn-warning" type="submit">Update</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

{% block javascript %}
    <script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format:'YYYY-MM-DD'
            });
        });
    </script>
{% endblock javascript %}

src/genius/templates/genius/students.html
{% extends 'base.html' %}

{% block content %}
<style>
.my-custom-scrollbar {
position: relative;
height: 400px;
overflow: auto;
}
</style>

     <div class="row pull-right mb-4">
        <form class="form-inline my-3 my-lg-2 mr-2" action="{% url 'genius:std-search' %}">
            <input class="form-control mr-sm-2" name='q' type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-warning my-2 my-sm-0" type="search">Search</button>
        </form> 
    </div>
    <div class="row ml-4">
    <p>
        <button class="btn btn-primary" type="button">
            Print Documents
        </button>
        <a class="btn btn-success ml-3 right" href="{% url 'genius:stds-new' %}">Register New Student</a>
        <div class="col-md-3 mb-4 justify-content-center">
            <div class="card text-center bg-warning text-dark">
                <div class="card-header head justify">Students So Far: <p class="badge badge-warning text-wrap ml-2"> {{count}}</p></div> 
                </div>
            </div>
        </div>
    </p> 
    
    </div>
    
<div class="card-dark card-body">
    {% if students %}
        <div class="table-custom-scroll-y my-custom-scrollbar">
            <table class="table table-bordered table-striped mb-0 table-primary">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">DOB</th>
                        <th scope="col">Age</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Grade</th>
                        <th scope="col">School</th>
                        <th scope="col">Address</th>
                    </tr>
                </thead>
                <tbody >
                    {% for i in students %}
                        <tr>
                        <th scope="row">{{i.id}}</th>
                        <td><a href="/stds/{{i.id}}"">{{i.name}}</a></td>
                        <td>{{i.dob}}</td>
                        <td>{{i.age}}</td>
                        <td>{{i.gender}}</td>
                        <td>{{i.grade}}</td>
                        <td>{{i.attending_school}}</td>
                        <td>{{i.address}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
    <p class="lead justify">There are no students...</p>
    {% endif %}
</div>

{% endblock content %}

src/genius/templates/genius/students_delete.html
{% extends 'base.html' %}

{% block content %}
<h1> Are you sure you want to delete the following class?</h1>
<p class="lead">Student Name : {{obj.name}}<br>DOB : {{obj.dob}} <br>> Course : {{obj.course.class_name}}<br>Time : {{obj.course.from_time}} to {{obj.course.to_time}}</p>
<form method="POST" action=".">
{% csrf_token %}
<button class="btn btn-danger">Yes, Delete</button>
</form>
{% endblock content %}